module.exports = {
    // Table Names
    COUPONS_TABLE_NAME: 'Coupons',
    ENCRYPTED_DATA_TABLE_NAME: 'Encrypted_Data',
    ORDER_ITEMS_TABLE_NAME: 'Order_Items',
    ORDER_SUMMARY_TABLE_NAME: 'Order_Summary',
    RESTAURANTS_AND_REVIEWS_TABLE_NAME: 'Restaurants_and_Reviews',
    RESTAURANT_MENU_TABLE_NAME: 'Restaurant_Menu',
    // Index Names
    ORDER_SUMMARY_USER_ID_INDEX: 'user_id-order_id-index',
    ORDER_SUMMARY_DRIVER_ID_INDEX: 'driver_id-order_id-index',
    ORDER_SUMMARY_RESTAURANT_ID_INDEX: 'restaurant_id-order_id-index',
    // Column Names
    ADDRESS: 'address',
    APP_EARNING: 'app_earning',
    CLOSE_TIME: 'close_time',
    CONTACT: 'contact',
    COUPON_ID: 'coupon_id',
    COUPON_USED: 'coupon_used',
    COUPON_VALUE: 'coupon_value',
    CREATED_AT: 'created_at',
    CUISINE: 'cuisine',
    DATE_TIME: 'date_time',
    DESCRIPTION: 'description',
    DETAILS: 'DETAILS',
    DRIVER_ID: 'driver_id',
    DRIVER_EARNING: 'driver_earning',
    EMAIL: 'email',
    ENCRYPTED_CREDENTIAL: 'encrypted_credential',
    ENCRYPTED_PAYMENT: 'encrypted_payment',
    EXPIRATION_TIME: 'expiration_time',
    FINAL_PRICE: 'final_price',
    ITEM_ID: 'item_id',
    ITEM_NAME: 'item_name',
    ITEM_PRICE: 'item_price',
    MINIMUM_ORDER: 'minimum_order',
    OPEN_TIME: 'open_time',
    ORDER_ID: 'order_id',
    ORDER_TYPE: 'order_type',
    PAYMENT: 'payment',
    PAYMENT_NAME: 'payment_name',
    PRIMARY_KEY: 'pk',
    QUANTITY: 'quantity',
    RATING: 'rating',
    RESTAURANT_ADDRESS: 'restaurant_address',
    RESTAURANT_EARNING: 'restaurant_earning',
    RESTAURANT_ID: 'restaurant_id',
    RESTAURANT_NAME: 'restaurant_name',
    REVIEW: 'review',
    SORT_KEY: 'sk',
    USED: 'used',
    USER_ID: 'user_id',
    USER_NAME: 'user_name',
    USER_TYPE: 'user_type',
}